services:

  crud:
    build:
      context: ./crud
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 3011
    container_name: crud
    restart: always
    networks:
      - programmator_network
    environment:
      PORT: 3011
      FILES_DIR: /root/crud/files
    ports:
      - '3011:3011'
    volumes:
      - ./crud/files:/root/crud/files

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 4001
    container_name: backend
    environment:
      PORT: 4001
      CRUD_URL: http://crud
      CRUD_PORT: 3011
    restart: always
    networks:
      - programmator_network
    ports:
      - '4001:4001'



networks:
  programmator_network:
    name: programmator_network